// docs/src/components/SocialProof.svelte
<script>

    const logos = [
        { name: 'Uniswap', src: '/uniswap.png', url: 'https://uniswap.org/' },
        { name: 'SushiSwap', src: '/sushiswap.png', url: 'https://sushi.com/' },
        { name: 'PancakeSwap', src: '/pancakeswap.png', url: 'https://pancakeswap.finance/' },
        { name: 'Vortex', src: '/vortex.png', url: 'https://vortexfinance.co/' },
        { name: 'Pendulum', src: '/pendulum.png', url: 'https://portal.pendulumchain.org/' },
        { name: 'beefy', src: '/beefy.png', url: 'https://beefy.com/' },
        { name: 'Curve Finance', src: '/curvefi.png', url: 'https://curve.fi/' },
        { name: 'Hydration', src: '/hydration.svg', url: 'https://hydration.net/' },
        { name: 'Aave', src: '/aave.png', url: 'https://aave.com/' },
    ];
</script>

<div class="py-16 border rounded-xl border-gray-200 dark:border-[#23272b] bg-gray-50 dark:bg-[#181a1b]/50 hover:scale-[1.02] transition-transform duration-300">
    <div class="text-center max-w-3xl mx-auto mb-10 px-4">
        <h2 class="text-2xl font-bold text-gray-900 dark:text-white mb-4">We analyzed the industry leaders.</h2>
        <p class="text-gray-600 dark:text-[#a0a3c4]">
            We didn't guess how to handle money, <strong>we analyzed the DeFi leaders.</strong> Numora’s core logic is a unification of the audited, hardened implementations used in the most trusted protocols in DeFi. We extracted the logic, removed the framework dependencies, and standardized the API.
        </p>
    </div>

    <div class="flex flex-wrap justify-center items-center gap-8 md:gap-16 px-4">
        {#each logos as logo}
            <a href={logo.url} target="_blank" rel="noopener noreferrer" class="group transition-all duration-300">
                <img
                    src={logo.src}
                    alt={logo.name}
                    class="social-logo h-8 md:h-12 w-auto opacity-60 group-hover:opacity-100 "
                />
            </a>
        {/each}
    </div>
</div>

<style>
  .social-logo {
    filter: grayscale(1) sepia(1) hue-rotate(250deg) saturate(4);
  }

  .group:hover .social-logo {
    filter: none;
  }
</style>

// docs/src/components/social-proof.tsx
import aaveLogo from '@/assets/defi/aave.png'
import beefyLogo from '@/assets/defi/beefy.png'
import curvefiLogo from '@/assets/defi/curvefi.png'
import pancakeswapLogo from '@/assets/defi/pancakeswap.png'
import pendulumLogo from '@/assets/defi/pendulum.png'
import sushiswapLogo from '@/assets/defi/sushiswap.png'
import uniswapLogo from '@/assets/defi/uniswap.png'
import vortexLogo from '@/assets/defi/vortex.png'
import hydrationLogo from '@/assets/tokens/hydration.svg'

const logos = [
  { name: 'Uniswap', src: uniswapLogo, url: 'https://uniswap.org/' },
  { name: 'SushiSwap', src: sushiswapLogo, url: 'https://sushi.com/' },
  { name: 'PancakeSwap', src: pancakeswapLogo, url: 'https://pancakeswap.finance/' },
  { name: 'Vortex', src: vortexLogo, url: 'https://vortexfinance.co/' },
  { name: 'Pendulum', src: pendulumLogo, url: 'https://portal.pendulumchain.org/' },
  { name: 'beefy', src: beefyLogo, url: 'https://beefy.com/' },
  { name: 'Curve Finance', src: curvefiLogo, url: 'https://curve.fi/' },
  { name: 'Hydration', src: hydrationLogo, url: 'https://hydration.net/' },
  { name: 'Aave', src: aaveLogo, url: 'https://aave.com/' },
]

export function SocialProof() {
  return (
    <div className="py-12 sm:py-16 px-4 sm:px-16 my-16 border rounded-xl border-[#23272b] bg-[#181a1b]/80 hover:scale-[1.02] transition-transform duration-300">
        <div className="text-center max-w-3xl mx-auto mb-10 px-4">
          <h2 className="text-3xl mb-4">
            We analyzed the industry leaders.
          </h2>
          <p>
            We didn't guess how to handle money, <strong>we analyzed the DeFi leaders.</strong> Numora's core logic is a unification of the audited, hardened implementations used in the most trusted protocols in DeFi. We extracted the logic, removed the framework dependencies, and standardized the API.
          </p>
        </div>

        <div className="flex flex-wrap justify-center items-center gap-8 md:gap-16 px-4">
          {logos.map((logo) => (
            <a
              key={logo.name}
              href={logo.url}
              target="_blank"
              rel="noopener noreferrer"
              className="social-logo-group transition-all duration-300"
            >
              <img
                src={logo.src}
                alt={logo.name}
                className="social-logo h-12 w-auto opacity-60"
              />
            </a>
          ))}
        </div>
    </div>
  )
}
